[tool.poetry]
name = "oflex-bot-dofus"
version = "1.0.0"
description = ""
authors = ["ephell"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.6"
keyboard = "^0.13.5"
paddleocr = "^2.7.0.3"
paddlepaddle = "^2.5.2"
pynput = "^1.7.6"
pyautogui = "^0.9.54"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
