from enum import Enum


class Status(Enum):

    SUCCESSFULLY_RECALLED = "successfully_recalled"
    SUCCESSFULLY_ENTERED_BANK = "successfully_entered_bank"
    SUCCESSFULLY_OPENED_BANK_VAULT = "successfully_opened_bank_vault"
    SUCCESSFULLY_LEFT_BANK = "successfully_left_bank"
    SUCCESSFULLY_DEPOSITED_ITEMS_IN_TAB = "successfully_deposited_items_in_tab"
    SUCCESSFULLY_DEPOSITED_ALL_TABS = "successfully_deposited_all_tabs"
    SUCCESSFULLY_FINISHED_BANKING = "successfully_finished_banking"
    SUCCESSFULLY_TRAVERSED_MAP = "successfully_traversed_map"
    SUCCESSFULLY_STARTED_COMBAT = "successfully_started_combat"
    SUCCESSFULLY_FINISHED_HUNTING = "successfully_finished_hunting"
    SUCCESSFULLY_CLOSED_BANK_VAULT = "successfully_closed_bank_vault"
    SUCCESSFULLY_OPENED_BANKER_DIALOGUE = "successfully_opened_banker_dialogue"
    SUCCESSFULLY_SELECTED_CONSULT_YOUR_PERSONAL_SAFE = "successfully_selected_consult_your_personal_safe"
    SUCCESSFULLY_DETECTED_IF_ITEM_SPRITES_HAVE_LOADED = "successfully_detected_if_item_sprites_have_loaded"
    SUCCESSFULLY_DETECTED_BANKER_NPC = "successfully_detected_banker_npc"

    FAILED_TO_DETECT_LOADING_SCREEN_AFTER_RECALL = "failed_to_detect_loading_screen_after_recall"
    FAILED_TO_DETECT_LOADING_SCREEN_AFTER_CHANGE_MAP = "failed_to_detect_loading_screen_after_change_map"
    FAILED_TO_RECALL = "failed_to_recall"
    FAILED_TO_ENTER_BANK = "failed_to_enter_bank"
    FAILED_TO_LEAVE_BANK = "failed_to_leave_bank"
    FAILED_TO_OPEN_BANK_VAULT = "failed_to_open_bank_vault"
    FAILED_TO_CLOSE_BANK_VAULT = "failed_to_close_bank_vault"
    FAILED_TO_DETECT_BANKER_NPC = "failed_to_detect_banker_npc"
    FAILED_TO_OPEN_BANKER_DIALOGUE = "failed_to_open_banker_dialogue"
    FAILED_TO_OPEN_TAB = "failed_to_open_tab"
    FAILED_TO_DEPOSIT_ITEMS_IN_TAB = "failed_to_deposit_items_in_tab"
    FAILED_TO_DEPOSIT_ALL_TABS = "failed_to_deposit_all_tabs"
    FAILED_TO_DEPOSIT_SLOT = "failed_to_deposit_slot"
    FAILED_TO_DETECT_IF_ITEM_SPRITES_HAVE_LOADED = "failed_to_detect_if_item_sprites_have_loaded"
    FAILED_TO_GET_OCCUPIED_BANK_PODS = "failed_to_get_occupied_bank_pods"
    FAILED_TO_GET_OCCUPIED_INVENTORY_PODS_PERCENTAGE = "failed_to_get_occupied_inventory_pods_percentage"
    FAILED_TO_FINISH_BANKING = "failed_to_finish_banking"
    FAILED_TO_TRAVERSE_MAP = "failed_to_traverse_map"
    FAILED_TO_LEAVE_LUMBERJACK_WORKSHOP = "failed_to_leave_lumberjack_workshop"
    FAILED_TO_CHANGE_MAP = "failed_to_change_map"
    FAILED_TO_FINISH_HUNTING = "failed_to_finish_hunting"
    FAILED_TO_CHANGE_MAP_BACK_TO_ORIGINAL = "failed_to_change_map_back_to_original"
    FAILED_TO_SELECT_CONSULT_YOUR_PERSONAL_SAFE = "failed_to_select_consult_your_personal_safe"

    CHAR_DOESNT_HAVE_RECALL_POTION = "char_doesnt_have_recall_potion"
    NO_NEED_TO_RECALL = "no_need_to_recall"
    NO_ITEMS_TO_DEPOSIT_IN_TAB = "no_items_to_deposit_in_tab"
    ARRIVED_AT_ASTRUB_BANK_MAP = "arrived_at_astrub_bank_map"
    MAP_FULLY_SEARCHED = "map_fully_searched"
    REACHED_PODS_LIMIT = "reached_pods_limit"
    CHARACTER_IS_ON_NO_RECALL_MAP = "character_is_on_no_recall_map"
    CHARACTER_IS_NOT_ON_NO_RECALL_MAP = "character_is_not_on_no_recall_map"
