from enum import Enum


class Status(Enum):

    SUCCESSFULLY_FINISHED_FIGHTING = "successfully_finished_fighting"
    SUCCESSFULLY_DETECTED_TURN = "successfully_detected_turn"
    SUCCESSFULLY_SHRUNK_TURN_BAR = "successfully_shrunk_turn_bar"
    SUCCESSFULLY_UNSHRUNK_TURN_BAR = "successfully_unshrunk_turn_bar"
    SUCCESSFULLY_DISABLED_MODELS = "successfully_disabled_models"
    SUCCESSFULLY_FINISHED_FIRST_TURN_SPELL_CASTING = "successfully_finished_first_turn_spell_casting"
    SUCCESSFULLY_HANDLED_FIRST_TURN_ACTIONS = "successfully_handled_first_turn_actions"
    SUCCESSFULLY_MOVED_CHARACTER = "successfully_moved_character"
    SUCCESSFULLY_SELECTED_SPELL = "successfully_selected_spell"
    SUCCESSFULLY_CAST_SPELL = "successfully_cast_spell"
    SUCCESSFULLY_TURNED_ON_TACTICAL_MODE = "successfully_turned_on_tactical_mode"
    SUCCESSFULLY_FINISHED_SUBSEQUENT_TURN_SPELL_CASTING = "successfully_finished_subsequent_turn_spell_casting"
    SUCCESSFULLY_CAST_CORE_SPELLS = "successfully_cast_core_spells"
    SUCCESSFULLY_CAST_NON_CORE_SPELLS = "successfully_cast_non_core_spells"
    SUCCESSFULLY_HANDLED_BRAMBLE = "successfully_handled_bramble"
    SUCCESSFULLY_HANDLED_SUBSEQUENT_TURN_ACTIONS = "successfully_handled_subsequent_turn_actions"
    SUCCESSFULLY_CLOSED_FIGHT_RESULTS_WINDOW = "successfully_closed_fight_results_window"

    FAILED_TO_GET_TURN_INDICATOR_ARROW_LOCATION = "failed_to_get_turn_indicator_arrow_location"
    FAILED_TO_GET_TACTICAL_MODE_TOGGLE_ICON_POS = "failed_to_get_tactical_mode_toggle_icon_pos"
    FAILED_TO_GET_MODELS_TOGGLE_ICON_POS = "failed_to_get_models_toggle_icon_pos"
    FAILED_TO_GET_SPELL_ICON_POS = "failed_to_get_spell_pos"
    FAILED_TO_SELECT_SPELL = "failed_to_select_spell"
    FAILED_TO_CAST_SPELL = "failed_to_cast_spell"
    FAILED_TO_FINISH_FIGHTING = "failed_to_finish_fighting"
    FAILED_TO_DISABLE_MODELS = "failed_to_disable_models"
    FAILED_TO_GET_CHARACTER_POS_BY_CIRCLES = "failed_to_get_character_pos_by_circles"
    FAILED_TO_DETECT_IF_DESTINATION_CELL_IS_HIGHIGHTED = "failed_to_detect_if_destination_cell_is_highighted"
    FAILED_TO_MOVE_CHARACTER_DURING_FIRST_TURN = "failed_to_move_character_during_first_turn"
    FAILED_TO_GET_CHARACTER_POS_BY_TURN_BAR = "failed_to_get_character_pos_by_turn_bar"
    FAILED_TO_HANDLE_FIRST_TURN_ACTIONS = "failed_to_handle_first_turn_actions"
    FAILED_FIRST_TURN_SPELL_CASTING_MODELS_TOGGLE_ICON_VISIBLE = "failed_first_turn_spell_casting_models_toggle_icon_visible"
    FAILED_FIRST_TURN_SPELL_CASTING_MODELS_TOGGLE_ICON_NOT_VISIBLE = "failed_first_turn_spell_casting_models_toggle_icon_not_visible"
    FAILED_TO_CAST_CORE_SPELLS = "failed_to_cast_core_spells"
    FAILED_TO_CAST_NON_CORE_SPELLS = "failed_to_cast_non_core_spells"
    FAILED_TO_HANDLE_SUBSEQUENT_TURN_ACTIONS = "failed_to_handle_subsequent_turn_actions"
    FAILED_TO_CLOSE_FIGHT_RESULTS_WINDOW = "failed_to_close_fight_results_window"
    FAILED_TO_DETECT_AP_COUNTER = "failed_to_detect_ap_counter"

    TIMED_OUT_WHILE_TURNING_ON_TACTICAL_MODE = "timed_out_while_turning_on_tactical_mode"
    TIMED_OUT_WHILE_DISABLING_MODELS = "timed_out_while_disabling_models"
    TIMED_OUT_WHILE_DETECTING_IF_SPELL_CAST_SUCCESSFULLY = "timed_out_while_detecting_if_spell_cast_successfully"
    TIMED_OUT_WHILE_WAITING_FOR_INFO_CARD_TO_APPEAR = "timed_out_while_waiting_for_info_card_to_appear"
    TIMED_OUT_WHILE_DETECTING_IF_CHARACTER_MOVED = "timed_out_while_detecting_if_character_moved"
    TIMED_OUT_WHILE_DETECTING_TURN = "timed_out_while_detecting_turn"
    TIMED_OUT_WHILE_SHRINKING_TURN_BAR = "timed_out_while_shrinking_turn_bar"
    TIMED_OUT_WHILE_UNSHRINKING_TURN_BAR = "timed_out_while_unshrinking_turn_bar"

    TACTICAL_MODE_IS_ALREADY_ON = "tactical_mode_is_already_on"
    MODELS_TOGGLE_ICON_NOT_VISIBLE = "models_toggle_icon_not_visible"
    CHARACTER_IS_ALREADY_ON_CORRECT_CELL = "character_is_already_on_correct_cell"
    SPELL_IS_NOT_CASTABLE_ON_PROVIDED_POS = "spell_is_not_castable_on_provided_pos"
    NO_SPELLS_AVAILABLE = "no_spells_available"
    FIGHT_RESULTS_WINDOW_DETECTED = "fight_results_window_detected"
    LOGIN_SCREEN_DETECTED = "login_screen_detected"
